apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-helm
  namespace: argocd
spec:
  project: default
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.13.3
    helm:
      releaseName: cert-manager
      values: |
        installCRDs: true
        
        global:
          leaderElection:
            namespace: cert-manager
        
        # Prometheus monitoring
        prometheus:
          enabled: true
          servicemonitor:
            enabled: false
        
        # Webhook configuration
        webhook:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
