apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-ddns-secret
  namespace: cloudflare-ddns
type: Opaque
stringData:
  CLOUDFLARE_API_TOKEN: "YOUR_CLOUDFLARE_API_TOKEN"  # Replace with your Cloudflare API token
  ZONE_NAME: "woxie.xyz"
